Stat svc
UserNameToHub/java-explore-with-me pull request #3
Opened 2023-09-08 20:28 UTC by UserNameToHub

Привет! Посмотри пжл. Не могу понять, что с маппингом ДТОшки не так

2023-09-11 04:46 UTC, EugeneLenkevich requested changes
Привет, Александр! Спасибо за PR.

На счет тестов уточни лучше сразу у наставника
Я сами ошибки(стектрейс) не вижу, но судя по всему что то где то не по ТЗ возвращается :)

![image](https://github.com/UserNameToHub/java-explore-with-me/assets/109306643/9b51f339-1579-4e5a-acf2-4fe8affd726d)

2023-09-11 04:46 UTC, EugeneLenkevich commented on stats-server/client/src/main/java/ru/practicum/stats/service/StateServiceImpl.java
> +    public ResponseEntity<Object> get(LocalDateTime start, LocalDateTime end, List<String> uris, boolean unique) {
ResponseEntity - это уровень контроллеров, давай тут вернем сами Dto

2023-09-11 04:46 UTC, EugeneLenkevich commented on pom.xml
> +<!--				<plugin>-->
Закомментированный код менее читаем и понятен для других разработчиков, что может привести к ошибкам и проблемам при компиляции или выполнении программы. Поэтому рекомендуется всегда удалять закомментированный код из своего кода программы.

Ну и, скорее всего, все вокруг поменяется и он станет не актуальным, а для истории есть git :)

2023-09-11 04:46 UTC, EugeneLenkevich commented on stats-server/client/src/main/java/ru/practicum/stats/StatsController.java
> +    public ResponseEntity<Object> creat(@RequestBody @Valid HitDto shortHit) {
_**creat**(@RequestBody @Valid HitDto shortHit)_

create

2023-09-11 18:11 UTC, EugeneLenkevich commented on stats-server/client/src/main/java/ru/practicum/stats/service/StateServiceImpl.java
> +    public ResponseEntity<Object> get(LocalDateTime start, LocalDateTime end, List<String> uris, boolean unique) {
> Ну да, на контроллере, это его обязанность :)

2023-09-11 18:24 UTC, UserNameToHub commented on stats-server/client/src/main/java/ru/practicum/stats/service/StateServiceImpl.java
> +    public ResponseEntity<Object> get(LocalDateTime start, LocalDateTime end, List<String> uris, boolean unique) {
Привет! Спасибо! Подскажи пжл, здесь я не совсем понял) Если в сервисе мы вернем Dto, то формировать responseEntity придется в контроллере? И если так, то зачем тогда сервисы?

2023-09-11 18:42 UTC, EugeneLenkevich commented on stats-server/client/src/main/java/ru/practicum/stats/service/StateServiceImpl.java
> +    public ResponseEntity<Object> get(LocalDateTime start, LocalDateTime end, List<String> uris, boolean unique) {
Дело в том что учебный проект достаточно тривиальный, в нем нет большого количества логики, потому и кажется что мы пишем кучу какого то избыточного кода :)
В реальной жизни там будет куча сопутствующей логики, например проверки прав пользователя, аудирование, вспомогательные вызовы других сервисов и пр

2023-09-11 19:11 UTC, UserNameToHub commented on stats-server/client/src/main/java/ru/practicum/stats/service/StateServiceImpl.java
> +    public ResponseEntity<Object> get(LocalDateTime start, LocalDateTime end, List<String> uris, boolean unique) {
Написал наставнику) Но, может ты еще посмотришь, стектрейс прикрепил.

2023-09-14 03:31 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-14 10:55 UTC, merged