Main svc
UserNameToHub/java-explore-with-me pull request #4
Opened 2023-10-10 00:05 UTC by UserNameToHub

2023-10-11 18:30 UTC, EugeneLenkevich requested changes
Привет, Александр! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-10-11 20:48 UTC, UserNameToHub commented on ewm-service/src/main/java/ru/practicum/event/entity/Event.java
> +@Data
Я так понял, при ввызове метода toString у объекта Event будут генериться забпросы чтобы получить toString у полей с @manyToOne? Поправил) Исключил поля из текстового представления.

Использую аннотацию @EqualsAndHashCode(of = "id"), чтобы генерить хеш и иклс по id)

2023-10-11 20:48 UTC, UserNameToHub commented on ewm-service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +        return userMapper.toDto(userRepository.save(userMapper.toEntity(newUserDto)));
Поправил)

2023-10-12 04:43 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/event/entity/Event.java
> +@Data
> Я так понял, при ввызове метода toString у объекта Event будут генериться забпросы чтобы получить toString у полей с @manytoone? 

Именно, это как раз тот момент когда абстракция течет, а любой ORM - это абстракция :)

2023-10-12 04:44 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-10-12 10:11 UTC, merged